name: Perform checks

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: |
        docker build -t vazeeapp/actions-k8s-manifests-validate-kubeval:${{ github.sha }} .
    - name: Run check
      run: |
        docker run -v example:/example vazeeapp/actions-k8s-manifests-validate-kubeval:${{ github.sha }} "/example" "master" "true" "false" "true" "false" ""
